version: '3.9'

networks:
  quiz-network:

services:
  web-java:
    build:
      context: .
      dockerfile: docker/Dockerfile-deploy
    container_name: server
    ports:
      - '3000:8080'
    depends_on:
      - database
    networks:
      - quiz-network

  database:
    image: mysql:5.7.16
    container_name: quiz-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "quiz"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - quiz-network