FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
COPY pom.xml pom.xml
RUN mvn dependency:go-offline
COPY /src src
RUN mvn -f pom.xml clean package

FROM openjdk:17.0.1-slim-buster
RUN apt-get update && apt-get install -y netcat
RUN mkdir /opt/user-photos
RUN useradd spring
RUN chown -R spring:spring /opt/user-photos
USER spring:spring
COPY --chown=spring:spring --from=build /app/target/*.jar /app/app.jar
COPY ./docker/init.sh .

ENTRYPOINT ["./init.sh"]